#!/bin/bash

killall set_up_101

umount -l /dev/pve/vm-101-disk-1

pct stop 101
pct unmount 101
pct destroy 101
pct create 101 /var/lib/vz/template/cache/ubuntu-16.04-standard_16.04-1_amd64.tar.gz --storage local-lvm --net0 name=eth0,bridge=vmbr0,ip=172.20.0.2/16,gw=172.20.0.1 --onboot 1 --nameserver 1.1.1.1 --searchdomain umd.edu --core 1 --cpulimit 0.5 --swap 0 --memory 512

pct unmount 101

pct start 101
pct mount 101

pct exec 101 -- apt-get install -y git build-essential autoconf libtool-bin socat
pct exec 101 -- bash -c "cd /root/ && git clone https://github.com/a2o/snoopy.git"
pct exec 101 -- bash -c "cd /root/snoopy/ && git submodule init && git submodule update && ./bootstrap.sh"
pct exec 101 -- bash -c "cd /root/snoopy/ && ./configure && make && make install && make enable"

sed -i "s/PermitRootLogin prohibit-password/PermitRootLogin yes/" /var/lib/lxc/101/rootfs/etc/ssh/sshd_config
echo  "root:root" | pct exec 101 chpasswd

pct exec 101 -- service ssh restart

pct stop 101
pct unmount 101
pct start 101
pct mount 101

pct exec 101 -- rm -rf /root/snoopy

#pct exec 101 -- wget -O snoopy-install.sh https://github.com/a2o/snoopy/raw/install/doc/install/bin/snoopy-install.sh
#pct exec 101 -- chmod 755 snoopy-install.sh
#pct exec 101 -- ./snoopy-install.sh stable

nohup ~/set_up_101 >> ~/output_101 &
