#!/bin/bash

killall node
killall set_up_102

pct stop 102
pct unmount 102

echo PLEASE STOP
umount -l /dev/pve/vm-102-disk-1

pct destroy 102
pct create 102 /var/lib/vz/template/cache/ubuntu-16.04-standard_16.04-1_amd64.tar.gz --storage local-lvm --net0 name=eth0,bridge=vmbr0,ip=172.20.0.3/16,gw=172.20.0.1 --onboot 1 --nameserver 1.1.1.1 --searchdomain umd.edu --core 1 --cpulimit 0.5 --swap 0 --memory 512
pct start 102
pct mount 102
sed -i "s/PermitRootLogin prohibit-password/PermitRootLogin yes/" /var/lib/lxc/102/rootfs/etc/ssh/sshd_config
echo  "root:proxmoxContainer@ACES" | pct exec 102 chpasswd

pct exec 102 -- service ssh restart

nohup ~/set_up_102 >> ~/output_102 &

